export const IMAGES = {
  // a
  appstore: '/qrCode/appstore.svg',
  // b
  bullet: '/upgrade/bullet.png',
  // c
  // d
  // e
  emptyProductOrder: '/nodata/emptyProductOrder.png',
  // f
  rocketBoy: '/dashboard/rocket-boy.png',
  rocketBoyGif: '/dashboard/rocket-boy-1.gif',
  // g
  googleplay: '/qrCode/googleplay.svg',
  groupUser: '/icon/GroupUser.png',
  // h
  // i
  // j
  // k
  // l
  // m
  mess: '/dashboard/mess.png',
  // n
  nodataShift: '/nodata/nodata-shift.png',
  noImage: '/nodata/noimagelogo.png',
  nodataStage: '/nodata/nodata-stage.png',
  nodataShiftSchedule: '/nodata/nodata-calendar.png',
  nodataNotFound: '/nodata/data-not-found.png',
  nodataChart: '/nodata/nodata-chart.png',
  nodataNoti: '/nodata/nodata-noti.png',
  // o
  // p
  // q
  qrDownloadApp: '/qrCode/qrDowloadApp.jpeg',
  // r
  // s
  summary_LSX: '/nodata/summaryLSX.webp',
  // t
  // u
  upgrade_pro: '/upgrade/upgrade.png',
  upgrade_pro_gif: '/upgrade/upgrade.gif',
  // v
  // w
  warningMobile: '/popup/Code.webp',
  // x
  // y
  // z
};
